### ISSUE TITLE
Merge this with ros/robot_state_publisher

### ISSUE THREAD

**Issue by sloretz** [ros2/robot_state_publisher#17]
I think there's been consensus to move away from forks, so this should be upstreamed to ros/robot_state_publisher (on a crystal branch?)

**Comment by clalancette** [comment]
Yes, definitely.  It's on my TODO list to get done, but at this point I probably won't get to it for a couple of weeks.  If you have time to do it, please go ahead!

**Comment by clalancette** [comment]
This is currently in progress.  I'm going to close this out so I can mark this repository read-only.
