### ISSUE TITLE
add ROS2 compatible tests for robot_state_publisher

### ISSUE THREAD

**Issue by Karsten1987** [ros2/robot_state_publisher#2]
Due to migration from ROS1 to ROS2, there're currently no tests.

**Comment by wjwwood** [comment]
I updated the title to be specific for `robot_state_publisher`. `map_server`'s tests were simple so I ported them from ROS 1.

**Comment by clalancette** [comment]
Migrated to https://github.com/ros/robot_state_publisher/issues/116 ; closing this out.
