### ISSUE TITLE
robot_description not being published in dashing

### ISSUE THREAD

**Issue by pbeeson** [ros2/robot_state_publisher#23]
I realize that there was already a closed issue about robot_description not being pushlished, but if you make a simple client following the code from [here:](https://github.com/ros2/robot_state_publisher/issues/14#issuecomment-466809516), it simply DOES NOT work.

Here is an entire sample program that I changed from the example "chatter" subscriber that I know works for default topics.

```
#include <iostream>
#include <memory>

#include "rclcpp/rclcpp.hpp"

#include "std_msgs/msg/string.hpp"

void chatterCallback(const std_msgs::msg::String::SharedPtr msg)
{
  std::cout << "I heard: [" << msg->data << "]" << std::endl;
}

int main(int argc, char * argv[])
{
  rclcpp::init(argc, argv);

  auto node = rclcpp::Node::make_shared("listener");
  auto qos = rmw_qos_profile_default;
  qos.durability = RMW_QOS_POLICY_DURABILITY_TRANSIENT_LOCAL;
 
  auto sub = node->create_subscription<std_msgs::msg::String>(
    "robot_description", chatterCallback, qos);

  rclcpp::spin(node);

  return 0;
}
```

This works for any standard (non-transient) publisher on /robot_description, but the message published by robot_state_publisher is never seen, even if you start it before/after this client node.

**Comment by pbeeson** [comment]
It also does not matter if you use this API or the new dashing API where qos is the 2nd argument.

**Comment by pbeeson** [comment]
OK, I see.  for whatever reason, the single, lone publish of robot_description on a topic is ONLY done in publishTransform, which ONLY happens in joint state callback is triggered.  This means that any standalone unit tests that want to do something like test kinematics from a urdf can't work as it did in ROS1.  What is the reasoning why model_xml_ cannot be published in the constructor of RobotStatePublisher?  that data structure never changes, so waiting until a joint_State arrives to publish is very limiting.

**Comment by pbeeson** [comment]
See https://github.com/ros2/robot_state_publisher/pull/24

This works as intended, in that unit test programs that need the URDF (but don't run with a robot/simulation started) can get and use the URDF without parsing it themselves (or perhaps use the wrong URDF in a complex scenario where many nodes use the URDF for various reasons (collision checking, kinematics, etc.)).

**Comment by clalancette** [comment]
Closing this out now that #24 has been merged.
